'use client'

import { QRCodeSVG } from 'qrcode.react'
import { ArrowLeft, Check, Copy, Mail } from 'lucide-react'
import type { TicketConfirmation } from '@/lib/pocketbase'

export function TicketConfirmationView({ ticket }: { ticket: TicketConfirmation }) {
  return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto max-w-3xl px-5 py-10 sm:px-8 sm:py-16"><a href="/#programme" className="inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft className="size-4" /> Back to programme</a><section className="mt-12 border border-border bg-card p-6 sm:p-10"><div className="flex items-center gap-3 text-accent"><span className="grid size-9 place-items-center rounded-full bg-accent text-accent-foreground"><Check className="size-5" /></span><p className="font-mono text-xs font-bold uppercase tracking-[0.18em]">Booking confirmed</p></div><h1 className="mt-6 font-serif text-5xl leading-none tracking-[-0.04em] sm:text-7xl">Your place is held.</h1><p className="mt-5 flex items-center gap-2 text-sm text-muted-foreground"><Mail className="size-4" /> A confirmation is ready for {ticket.attendeeEmail}</p><div className="mt-10 grid gap-8 border-y border-border py-8 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="font-mono text-xs uppercase tracking-[0.16em] text-muted-foreground">{ticket.event.title}</p><p className="mt-3 text-sm">{ticket.event.venue}</p><p className="mt-1 text-sm text-muted-foreground">Reference: {ticket.reference}</p><p className="mt-1 flex items-center gap-2 text-xs text-muted-foreground">Ticket hash: {ticket.qrHash.slice(0, 18)}... <Copy className="size-3" /></p></div><div className="border border-border bg-background p-4"><QRCodeSVG value={ticket.qrHash} size={150} aria-label="Your SICAF ticket QR code" /></div></div><p className="text-xs leading-6 text-muted-foreground">Show this QR code at the festival entrance. Keep your reference handy if you need help from the SICAF team.</p></section></div></main>
}
